# Generated by Django 5.2.6 on 2025-09-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_admission_number_customuser_college_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='admission_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
