# Generated by Django 5.2.6 on 2025-10-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='chat_status',
            field=models.CharField(choices=[('NONE', 'No Request'), ('REQUESTED', 'Requested by User'), ('ACCEPTED', 'Accepted by Admin'), ('DECLINED', 'Declined by Admin')], default='NONE', max_length=10),
        ),
    ]
