# Generated by Django 5.2.6 on 2025-10-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_grievance_chat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='grievance',
            name='evidence_image',
            field=models.ImageField(blank=True, null=True, upload_to='grievance_evidence/'),
        ),
    ]
