# Generated by Django 5.2.6 on 2025-10-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_customuser_profile_image_grievance_evidence_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='LOW', max_length=10),
        ),
    ]
