# Generated by Django 5.2.6 on 2025-10-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_chatmessage_grievance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievancecomment',
            name='evidence_file',
            field=models.FileField(blank=True, null=True, upload_to='grievance_evidence/'),
        ),
    ]
