# Generated by Django 5.2.6 on 2025-10-19 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_grievancecomment_evidence_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grievancecomment',
            name='evidence_file',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.conversation'),
        ),
    ]
