# Generated by Django 5.2.6 on 2025-10-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_chatmessage_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='evidence_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
