# Generated by Django 5.2.6 on 2025-10-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_customuser_profile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image_link',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='evidence_link',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='grievance',
            name='evidence_image',
            field=models.ImageField(blank=True, null=True, upload_to='grievance_evidence/'),
        ),
    ]
