# Generated by Django 5.2.6 on 2025-10-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_customuser_profile_image_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='evidence_image',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='evidence_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
