# Generated by Django 5.2.6 on 2025-10-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_customuser_profile_image_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('IN PROGRESS', 'In Progress'), ('ACTION_TAKEN', 'Action Taken'), ('RESOLVED', 'Resolved')], default='SUBMITTED', max_length=20),
        ),
    ]
